#!/bin/bash

bar(){
    cyan "--------------------------------------------------"
}

barNoColor(){
    echo "--------------------------------------------------"
}

setvstack(){
	cyan   "                                                  "
	cyan   "                       BYUS                       "
	purple "                    Technology                    "
	purple "        VStack (Automated server build up)        "
	blue   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
}

setvstackNoColor(){
	echo   "                                                  "
	echo   "                       BYUS                       "
	echo   "                    Technology                    "
	echo   "        VStack (Automated server build up)        "
	echo   "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
}