#!/bin/bash

. /etc/.vstack/includes/colors
. /etc/.vstack/includes/format

PHP="7.4"
MYSQL_SERVICE="MySQL"
MYSQL_PACKAGE="mysql-server"
INSTALL_REDIS=0

if [ "$2" = "php81" ] || [ "$3" = "php81" ]; then
   PHP="8.1"
elif [ "$2" = "php74" ] || [ "$3" = "php74" ]; then
   PHP="7.4"
elif [ "$2" = "php73" ] || [ "$3" = "php73" ]; then
   PHP="7.3"
elif [ "$2" = "php72" ] || [ "$3" = "php72" ]; then
   PHP="7.2"
elif [ "$2" = "php71" ] || [ "$3" = "php71" ]; then
   PHP="7.1"
fi

if [ "$2" = "mariadb" ] || [ "$3" = "mariadb" ]; then
   MYSQL_SERVICE="MariaDB"
   MYSQL_PACKAGE="mariadb-server"
fi

if [ "$2" = "redis" ] || [ "$3" = "redis" ]; then
   INSTALL_REDIS=1
fi

setvstack

bar
cyan "| Removing Apache from server";
bar
sudo service apache2 stop
sudo apt-get purge -y apache2 apache2-utils apache2.2-bin apache2-common
sudo apt-get purge -y apache2 apache2-utils apache2-bin apache2.2-common

bar
cyan "| Installing Nginx ";
bar

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx HTTPS'
sudo systemctl restart nginx

bar
cyan "| Installing $MYSQL_SERVICE ";
bar

MYSQLPASS=$(openssl rand -base64 32)
MYSQLUSER='dbadmin'

sudo apt-get update
if [ ! -d /etc/.vstack/tmp ]; then
  mkdir /etc/.vstack/tmp
fi


echo '[client]' > /home/vstack/.my.cnf
echo "user=${MYSQLUSER}" >> /home/vstack/.my.cnf
echo "password='${MYSQLPASS}'" >> /home/vstack/.my.cnf

chmod 600 /home/vstack/.my.cnf

sudo apt-get install -y ${MYSQL_PACKAGE}

sudo service mysql start
sudo mysql -uroot -p${MYSQLPASS} -e "CREATE USER ${MYSQLUSER}@localhost IDENTIFIED BY '${MYSQLPASS}'; GRANT ALL PRIVILEGES ON *.* TO ${MYSQLUSER}@localhost WITH GRANT OPTION;"

# Get current client IP address
CLIENT_IP=$(echo $SSH_CLIENT | awk '{ print $1}')

# Enable 3306 ports in order to connect to database via Sequel Pro
sudo ufw allow from ${CLIENT_IP}/32 to any port 3306

bar
cyan "| Installing PHP $PHP and all necessary files";
bar

sudo apt-get update
sudo apt-get install -y language-pack-en-base
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get install -y unzip
sudo apt-get install -y php-cli
sudo apt-get install -y php$PHP-cli php$PHP-common php$PHP-mysql php$PHP-gd php$PHP-mysql php$PHP-curl php$PHP-mbstring php$PHP-xml php$PHP-zip php$PHP-fpm curl git

sudo rm /usr/bin/php
sudo ln -s /usr/bin/php$PHP /usr/bin/php

bar
cyan "| Updating Permissions "
bar

sudo chown -R vstack:vstack /var/www

CHECK_SWAP=$(swapon -s | wc -l)
if [ $CHECK_SWAP -lt 1 ] ; then
    bar
    cyan "| Adding swap file "
    bar

    # Create a swap file
    sudo fallocate -l 1G /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile

    # Making the swap file permanent
    sudo cp /etc/fstab /etc/fstab.bak
    echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
fi


bar
cyan "| Installing Composer ";
bar

curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

bar
cyan "| Installing NPM"
bar

curl -sL https://deb.nodesource.com/setup_16.x | sudo bash -
sudo apt-get install -y nodejs

bar
cyan "| Adding the Laravel Installer "
bar

sudo chown -R $USER:$USER ~/.composer/
composer global require "laravel/installer"

bar
cyan "| Installing certbot ";
bar

sudo apt-get install -y python3 python3-venv libaugeas0 python3-pip
#Remove certbot in case it is already installed from the repository/ppa to avoid conflict
sudo apt-get remove --purge certbot python3-certbot-nginx

sudo python3 -m venv /opt/certbot/
sudo /opt/certbot/bin/pip install --upgrade pip
sudo /opt/certbot/bin/pip install certbot certbot-nginx
sudo rm -f /usr/bin/certbot
sudo ln -s /opt/certbot/bin/certbot /usr/bin/certbot

#Set up automatic certificate renewal
echo "0 0,12 * * * root /opt/certbot/bin/python -c 'import random; import time; time.sleep(random.random() * 3600)' && certbot renew -q" | sudo tee -a /etc/crontab > /dev/null


if [ $INSTALL_REDIS -eq 1 ] ; then
	bar
	cyan "| Installing Redis"
	bar

	sudo apt -y install redis-server
fi

setvstack

bar
cyan "| Finished! "
bar

bar
cyan "| Here is your server informations, do not forget it! "
bar

bar
cyan "| User $USER "
cyan "| PHP Version $PHP "
cyan "| Datbase service $MYSQL_SERVICE "
cyan "| Datbase user $MYSQLUSER "
cyan "| Datbase password $MYSQLPASS "
bar